<div class="groups-page container-fluid">
    <div class="row">
        <div class="col-lg-2"></div>

        <div class="create-form col-lg-7">
            <form ng-submit="addGroup(group)" class="form-inline">
                <div class="form-group">
                    <input ng-disabled="loading" ng-model="group" type="text" class="form-control" placeholder="Название группы" />
                </div>

                <button ng-disabled="loading || group == ''" type="submit" class="btn btn-default">Создать</button>

                <span ng-if="groupExists" class="text-danger" ng-cloak>Группа с таким названием уже существует</span>
            </form>
        </div>

        <div class="col-lg-3"></div>
    </div>

    <div list-table
         table="'/partial/groups/table'"
         fetch-items="fetchGroups"
         search-items="searchGroups"
         loading="loading"></div>
</div>
