<div class="groups-page container-fluid">
    <div class="row">
        <div class="col-sm-2"></div>

        <div class="page-title col-sm-5">
            <b>Группа:</b>

            <span ng-show="edit.title == false" ng-cloak>
                {{ groupInfo.title }}

                <a ng-click="edit.title = true" href="javascript:void(0);" class="no-underline" title="Изменить">
                    <span class="glyphicon glyphicon-edit"
                          aria-hidden="true"
                          data-toggle="modal"></span>
                </a><br>
            </span>

            <span ng-show="edit.title == true" ng-cloak>
                <form ng-submit="editGroup(edit.values)" class="edit-group-title" ng-class="{loading: edit.loading}">
                    <input type="text" ng-model="edit.values.title" ng-blur="edit.title = false" ng-disabled="edit.loading">
                </form><br>
            </span>

            <b>Посещений:</b>
            {{ groupInfo.stat_count }}
        </div>

        <div class="col-sm-3">
            <div period-chooser></div>
        </div>

        <div class="col-sm-2"></div>
    </div>

    <div visits-chart
         fetch-items="fetchVisitsByGroup"></div>

    <div list-table
         table="'/partial/groups/info-table'"
         fetch-items="fetchLinks"
         search-items="searchLinks"
         loading="loading"
         redirect="redirect"
         items-per-page="10"></div>
</div>
