<div class="groups-page container-fluid">
    <div class="row">
        <div class="col-lg-2"></div>

        <div class="page-title col-lg-7">
            <a href="javascript:void(0);" ng-click="historyBack()">
                <span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span>
                Назад
            </a><br /><br />

            <b>Название:</b>
            {{ groupInfo.title }}<br />

            <b>Посещений:</b>
            {{ groupInfo.stat_count }}
        </div>

        <div class="col-lg-3"></div>
    </div>

    <div visits-chart
         fetch-items="fetchVisitsByGroup"></div>

    <div list-table
         table="'/partial/groups/info-table'"
         fetch-items="fetchLinks"
         search-items="searchLinks"
         loading="loading"
         redirect="redirect"
         items-per-page="10"></div>
</div>
