<div class="groups-page container-fluid">
    <div class="row">
        <div class="col-lg-2"></div>

        <div class="page-title col-lg-7">
            <a href="javascript:void(0);" ng-click="historyBack()">
                <span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span>
                Назад
            </a>
            <br/><br/>

            <b>Название:</b>
            {{ groupTitle }}
        </div>

        <div class="col-lg-3"></div>
    </div>
</div>
