<table class="table table-hover table-condensed">
    <thead>
        <tr>
            <th>Название</th>
            <th class="align-center">Ссылок</th>
            <th class="align-center">Посещений</th>
        </tr>
    </thead>
    <tbody>
        <tr ng-repeat="group in search.active ? search.items : items" ng-click="redirect('/admin/groups/' + group.id, $event)" class="row-link" ng-cloak>
            <td>
                <div class="full-width">
                    <a ng-href="/admin/groups/{{ group.id }}" ng-click="redirect('/admin/groups/' + group.id, $event)">{{ group.title }}</a>
                </div>
            </td>
            <td class="align-center">
                {{ group.links_count }}
            </td>
            <td class="align-center">
                {{ group.stat_count }}
            </td>
        </tr>
    </tbody>
</table>
