<div class="stat-page container-fluid">
    <div class="row">
        <div class="col-sm-2"></div>

        <div class="page-title col-sm-5">
            <a href="javascript:void(0);" ng-click="historyBack()">
                <span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span>
                Назад
            </a><br /><br />

            <b>Ссылка:</b>
            <a ng-click="copyToClipboard(info.link, $event)"
               ng-href="{{ info.link }}"
               class="copy-enable"
               title="Скопировать">{{ info.link }}</a><span class="glyphicon glyphicon-copy" aria-hidden="true"></span><br />

            <b>Короткая ссылка:</b>
            <a ng-click="copyToClipboard(info.short_link_full, $event)"
               ng-href="{{ info.short_link_full }}"
               class="copy-enable"
               title="Скопировать">{{ info.short_link_full }}</a><span class="glyphicon glyphicon-copy" aria-hidden="true"></span><br />

            <b>Группа:</b>
            <div ng-show="group.editEnabled == false" class="group-wrapper" ng-cloak>
                <a ng-href="/admin/group/{{ info.group_id }}">{{ info.group_title }}</a>

                <a href="javascript:void(0);" ng-click="group.editEnabled = true" title="Изменить">
                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                </a>
            </div>

            <div ng-show="group.editEnabled == true" class="group-wrapper" ng-cloak>
                <select ng-model="group.id" ng-change="groupChanged(group.id)" ng-blur="group.editEnabled = false" class="form-control">
                    <option ng-repeat="group in groups | orderBy: 'title'" ng-value="group.id">{{ group.title }}</option>
                </select>
            </div>
        </div>

        <div class="col-sm-3">
            <div period-chooser
                 period="period"></div>
        </div>

        <div class="col-sm-2"></div>
    </div>

    <div visits-chart
         fetch-items="fetchVisitsByLink"
         period="period"></div>

    <div list-table
         table="'/partial/stat/table'"
         fetch-items="fetchStat"></div>
</div>
