<!DOCTYPE html>
<html lang="ru" ng-app="main">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MIF Links</title>
    <base href="/" />

    <?php foreach ($this->_meta as $property => $content): ?>
        <meta name="<?= $property; ?>"
              property="<?= $property; ?>"
              content="<?= $content; ?>" />
    <?php endforeach; ?>

    <link href="/css/style.css" rel="stylesheet" />
    <script src="/js/app.js"></script>
</head>
<body>
<?= $this->content(); ?>
</body>
</html>
