<!DOCTYPE html>
<html lang="ru" ng-app="app">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MIF Links</title>
    <base href="/" />

    <?php foreach ($this->_meta as $property => $content): ?>
        <meta name="<?= $property; ?>"
              property="<?= $property; ?>"
              content="<?= $content; ?>" />
    <?php endforeach; ?>

    <link href="/css/style.css" rel="stylesheet" />
</head>
<body ng-controller="CommonCtrl">
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Переключить</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="/admin">MIF-Links</a>
        </div>

        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li ng-class="{active: location.pathname.substr(0, '/admin/link'.length) == '/admin/link'}"><a href="/admin/links">Ссылки</a></li>
                <li ng-class="{active: location.pathname.substr(0, '/admin/group'.length) == '/admin/group'}"><a href="/admin/groups">Группы</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="layout" ng-view></div>

<script src="/js/app.js?rev=1"></script>
<script src="/js/angular-locale_ru-ru.js"></script>
</body>
</html>
