<div class="container-fluid">
    <div class="row">
        <div class="col-lg-2"></div>

        <div class="col-lg-6">
            <form ng-submit="generateLink(link)" class="form-inline">
                <div class="form-group">
                    <input ng-disabled="loading" ng-model="link" type="text" class="form-control" id="link" placeholder="http://">
                </div>

                <button ng-disabled="loading" type="submit" class="btn btn-default">Сгенерировать</button>
            </form>

            <div class="generated-link">
                <span ng-if="lastLink" ng-cloak>
                    Сгенерирована ссылка <a ng-href="{{ lastLink.shortLink }}" target="_blank">{{ lastLink.shortLink }}</a>
                    <a ng-click="regenerateLink(lastLink)" href="javascript:void(0);" title="Перегенерировать">
                        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
                    </a>
                </span>
            </div>
        </div>

        <div class="col-lg-4"></div>
    </div>

    <div ng-show="links.length" ng-style="{opacity : loading ? .4 : 1}" class="row" ng-cloak>
        <div class="col-lg-2"></div>

        <div class="col-lg-6">
            <table class="table table-hover table-condensed links-table">
                <thead>
                <th>Ссылка</th>
                <th>Короткая ссылка</th>
                </thead>
                <tbody>
                <tr ng-repeat="link in links" ng-cloak>
                    <td>
                        <a ng-href="{{ link.link }}" target="_blank">{{ link.link }}</a>
                    </td>
                    <td>
                        <a ng-href="{{ link.short_link }}" target="_blank">{{ link.short_link }}</a>
                    </td>
                </tr>
                </tbody>
            </table>

            <nav class="links-pager">
                <div class="info">{{ pager.from + 1 }}-{{ pager.to }} из {{ pager.count }}</div>

                <ul class="pager">
                    <li class="previous" ng-class="{disabled: pager.from == 0}">
                        <a ng-click="previousPage()" href="javascript:void(0);"><span aria-hidden="true">&larr;</span> Назад</a>
                    </li>

                    <li class="next" ng-class="{disabled: pager.to == pager.count}">
                        <a ng-click="nextPage()" href="javascript:void(0);">Вперёд <span aria-hidden="true">&rarr;</span></a>
                    </li>
                </ul>
            </nav>
        </div>

        <div class="col-lg-4"></div>
    </div>
</div>
