<div class="container">
    <div class="row">
        <div class="col-lg-2"></div>

        <div class="col-lg-6">
            <form ng-submit="generateLink(link)" class="form-inline">
                <div class="form-group">
                    <input ng-disabled="loading" ng-model="link" type="text" class="form-control" id="link" placeholder="http://">
                </div>

                <button ng-disabled="loading" type="submit" class="btn btn-default">Сгенерировать</button>
            </form>

            <div class="generated-link">
                <span ng-if="lastLink" ng-cloak>
                    Сгенерирована ссылка <a ng-click="copyToClipboard(lastLink.shortLink)" href="javascript:void(0);">{{ lastLink.shortLink }}</a>
                    <a ng-click="regenerateLink(lastLink)" href="javascript:void(0);" title="Перегенерировать">
                        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
                    </a>
                </span>
            </div>
        </div>

        <div class="col-lg-4"></div>
    </div>

    <div ng-show="links.length" ng-style="{opacity : loading ? .4 : 1}" class="row" ng-cloak>
        <div class="col-lg-2"></div>

        <div class="col-lg-6">
            <table class="links-table table table-hover table-condensed">
                <thead>
                <th>Ссылка</th>
                <th>Короткая ссылка</th>
                </thead>
                <tbody>
                <tr ng-repeat="link in links" ng-cloak>
                    <td>
                        <a ng-click="copyToClipboard(link.link)" href="javascript:void(0);">{{ link.link }}</a>
                    </td>
                    <td>
                        <a ng-click="copyToClipboard(link.short_link)" href="javascript:void(0);">{{ link.short_link }}</a>
                    </td>
                </tr>
                </tbody>
            </table>

            <nav class="links-pager">
                <div class="info">{{ pager.from + 1 }}-{{ pager.to }} из {{ pager.count }}</div>

                <ul class="pager">
                    <li class="previous" ng-class="{disabled: pager.from == 0}">
                        <a ng-click="previousPage()" href="javascript:void(0);"><span aria-hidden="true">&larr;</span> Назад</a>
                    </li>

                    <li class="next" ng-class="{disabled: pager.to == pager.count}">
                        <a ng-click="nextPage()" href="javascript:void(0);">Вперёд <span aria-hidden="true">&rarr;</span></a>
                    </li>
                </ul>
            </nav>
        </div>

        <div class="col-lg-4"></div>
    </div>
</div>

<div class="js-duplicate-popup duplicate-popup modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Короткая ссылка уже существует</h4>
            </div>

            <div class="modal-body">
                <table class="table table-condensed">
                    <tr ng-repeat="link in duplicates">
                        <td>
                            <a ng-click="copyToClipboard(link.short_link)" href="javascript:void(0);">{{ link.short_link }}</a>
                        </td>
                    </tr>
                </table>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                <button ng-click="generateLink(link, true)" type="button" class="btn btn-primary" data-dismiss="modal">Сгенерировать новую</button>
            </div>
        </div>
    </div>
</div>
