<table class="table table-hover table-condensed">
    <thead>
        <tr>
            <th>Ссылка</th>
            <th>Короткая ссылка</th>
            <th>Группа</th>
        </tr>
    </thead>
    <tbody>
        <tr ng-repeat="item in search.active ? search.items : items" ng-cloak>
            <td>
                <div class="full-width">
                    <a ng-href="/admin/stat/{{ item.id }}">{{ item.link }}</a>
                </div>
            </td>
            <td>
                <div class="full-width">
                    <a ng-click="copyToClipboard(item.short_link_full, $event)"
                       ng-href="{{ item.short_link_full }}"
                       class="copy-enable"
                       title="Скопировать">{{ item.short_link_full }}</a>

                    <span class="glyphicon glyphicon-copy" aria-hidden="true"></span>
                </div>
            </td>
            <td>
                {{ item.group_title }}
            </td>
        </tr>
    </tbody>
</table>
