<div class="period-chooser">
    <select ng-model="period.select" class="form-control pull-right">
        <option value="all-time" selected="true">Всё время</option>
        <option value="3-days">3 дня</option>
        <option value="week">Неделя</option>
        <option value="month">Месяц</option>
        <option value="dates">Указать период</option>
    </select>

    <div class="clear"></div>

    <div ng-show="period.select != 'all-time'" class="date-range" ng-cloak>
        <input type="text"
               ng-click="showDateRange=!showDateRange"
               ng-focus="inputFocus($event)"
               ng-model="period.text"
               class="pull-right">

        <div class="clear"></div>

        <div ng-show="showDateRange"
             date-range
             start="period.interval.start"
             end="period.interval.end"
             class="popup-date-range"
             ng-cloak></div>
    </div>
</div>
